/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Avatar: typeof import('./src/components/Avatar/index.vue')['default']
    Content: typeof import('./src/components/Message/content/index.vue')['default']
    DND: typeof import('./src/components/DND/index.vue')['default']
    Dropdown: typeof import('./src/components/Dropdown/index.vue')['default']
    LoginModal: typeof import('./src/components/LoginModal/index.vue')['default']
    Main: typeof import('./src/components/FullLoading/main.vue')['default']
    Message: typeof import('./src/components/Message/index.vue')['default']
    Modal: typeof import('./src/components/Modal/index.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NColorPicker: typeof import('naive-ui')['NColorPicker']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NInputGroup: typeof import('naive-ui')['NInputGroup']
    NInputGroupLabel: typeof import('naive-ui')['NInputGroupLabel']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NModal: typeof import('naive-ui')['NModal']
    NPagination: typeof import('naive-ui')['NPagination']
    NPopover: typeof import('naive-ui')['NPopover']
    NSelect: typeof import('naive-ui')['NSelect']
    NSlider: typeof import('naive-ui')['NSlider']
    NSpace: typeof import('naive-ui')['NSpace']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    NUpload: typeof import('naive-ui')['NUpload']
    PullAuthTip: typeof import('./src/components/PullAuthTip/index.vue')['default']
    QrPay: typeof import('./src/components/QrPay/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Slider: typeof import('./src/components/Slider/index.vue')['default']
    SystemModal: typeof import('./src/components/SystemModal/index.vue')['default']
    VideoControls: typeof import('./src/components/VideoControls/index.vue')['default']
    VPIconChevronDown: typeof import('./src/components/icons/VPIconChevronDown.vue')['default']
    VPIconExternalLink: typeof import('./src/components/icons/VPIconExternalLink.vue')['default']
  }
}
